### ISSUE TITLE
UnsupportedOperationException NULL

### ISSUE THREAD

**Issue by HexedHero** [Photon-GitHub/AACHider#10]
`[20:29:53 ERROR]: Could not pass event TabCompleteEvent to AACPlus v2.2.0
java.lang.UnsupportedOperationException: null
at com.google.common.collect.ImmutableCollection.removeIf(ImmutableCollection.java:270) ~[patched_1.15.2.jar:git-Paper-90]
at de.photon.aacplus.d.a(d.java:4) ~[?:?]
at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor412.execute(Unknown Source) ~[?:?]
at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.15.2.jar:git-Paper-90]
at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.15.2.jar:git-Paper-90]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.15.2.jar:git-Paper-90]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:559) ~[patched_1.15.2.jar:git-Paper-90]
at org.bukkit.craftbukkit.v1_15_R1.CraftServer.tabComplete(CraftServer.java:1713) ~[patched_1.15.2.jar:git-Paper-90]
at org.bukkit.craftbukkit.v1_15_R1.command.BukkitCommandWrapper.getSuggestions(BukkitCommandWrapper.java:49) ~[patched_1.15.2.jar:git-Paper-90]
at com.mojang.brigadier.tree.ArgumentCommandNode.listSuggestions(ArgumentCommandNode.java:71) ~[patched_1.15.2.jar:git-Paper-90]
at com.mojang.brigadier.CommandDispatcher.getCompletionSuggestions(CommandDispatcher.java:596) ~[patched_1.15.2.jar:git-Paper-90]
at com.mojang.brigadier.CommandDispatcher.getCompletionSuggestions(CommandDispatcher.java:579) ~[patched_1.15.2.jar:git-Paper-90]
at net.minecraft.server.v1_15_R1.PlayerConnection.lambda$a$3(PlayerConnection.java:566) ~[?:git-Paper-90]
at net.minecraft.server.v1_15_R1.TickTask.run(SourceFile:18) ~[patched_1.15.2.jar:git-Paper-90]
at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.15.2.jar:git-Paper-90]
at net.minecraft.server.v1_15_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.15.2.jar:git-Paper-90]
at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.15.2.jar:git-Paper-90]
at net.minecraft.server.v1_15_R1.MinecraftServer.ba(MinecraftServer.java:1038) ~[patched_1.15.2.jar:git-Paper-90]
at net.minecraft.server.v1_15_R1.MinecraftServer.executeNext(MinecraftServer.java:1031) ~[patched_1.15.2.jar:git-Paper-90]
at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeAll(IAsyncTaskHandler.java:95) ~[patched_1.15.2.jar:git-Paper-90]
at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:1172) ~[patched_1.15.2.jar:git-Paper-90]
at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:934) ~[patched_1.15.2.jar:git-Paper-90]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]`

**Comment by Photon-GitHub** [comment]
I am pretty sure that some plugin of yours overwrites the tab collection with an immutable one, even though the documentation explicitly states that it should be a mutable list. Please check your plugins.

**Comment by LogGits** [comment]
I seem to also be getting this issue. Could a solution be to set it as a new ArrayList of the existing immutable list?

**Comment by Photon-GitHub** [comment]
Yes, the plugin would have to set it to a mutable list and an ArrayList is mutable.
In that case AACPlus would not cause the errors.
However, as the documentation explicitly states that the list should be mutable the plugin author should fix that and not AACPlus.

**Comment by mbax** [comment]
I did some brief digging to help someone with plugin trouble and it looks like there's a scenario where Bukkit itself returns an ImmutableList. Check `Command#tabComplete0()`

**Comment by Photon-GitHub** [comment]
Fixed in 2.3.1
