### ISSUE TITLE
Unhandled exception occured in onPacketSending(PacketEvent) for AACPlus

### ISSUE THREAD

**Issue by PatoTheBest** [Photon-GitHub/AACHider#11]
### Issue Description
Please include a detailed description of the issue, instructions to reproduce it and relevant error logs or screenshots/videos.

AACPlus error handling packets

```
[20:16:02 ERROR]: [AACPlus] Unhandled exception number 64 occured in onPacketSending(PacketEvent) for AACPlus
java.lang.UnsupportedOperationException: The method getUniqueId is not supported for temporary players.
at com.comphenix.protocol.injector.server.TemporaryPlayerFactory$1.intercept(TemporaryPlayerFactory.java:144) ~[?:?]
at com.comphenix.protocol.injector.server.TemporaryPlayer$$EnhancerByCGLIB$$50f2ec48.getUniqueId(<generated>) ~[?:?]
at de.photon.aacplus.c.a(c.java:4) ~[?:?]
at de.photon.aacplus.a.onPacketSending(a.java:8) ~[?:?]
at com.comphenix.protocol.injector.SortedPacketListenerList.invokeSendingListener(SortedPacketListenerList.java:195) ~[?:?]
at com.comphenix.protocol.injector.SortedPacketListenerList.invokePacketSending(SortedPacketListenerList.java:149) ~[?:?]
at com.comphenix.protocol.injector.PacketFilterManager.handlePacket(PacketFilterManager.java:588) ~[?:?]
at com.comphenix.protocol.injector.PacketFilterManager.invokePacketSending(PacketFilterManager.java:564) ~[?:?]
at com.comphenix.protocol.injector.netty.ProtocolInjector.packetQueued(ProtocolInjector.java:338) ~[?:?]
at com.comphenix.protocol.injector.netty.ProtocolInjector.onPacketSending(ProtocolInjector.java:298) ~[?:?]
at com.comphenix.protocol.injector.netty.ChannelInjector.processSending(ChannelInjector.java:378) ~[?:?]
at com.comphenix.protocol.injector.netty.ChannelInjector.access$800(ChannelInjector.java:64) ~[?:?]
at com.comphenix.protocol.injector.netty.ChannelInjector$3.handleScheduled(ChannelInjector.java:343) ~[?:?]
at com.comphenix.protocol.injector.netty.ChannelInjector$3.onMessageScheduled(ChannelInjector.java:313) ~[?:?]
at com.comphenix.protocol.injector.netty.ChannelProxy$2.schedulingRunnable(ChannelProxy.java:127) ~[?:?]
at com.comphenix.protocol.injector.netty.EventLoopProxy.execute(EventLoopProxy.java:95) ~[?:?]
at net.minecraft.server.v1_15_R1.NetworkManager.b(NetworkManager.java:200) ~[patched_1.15.2.jar:git-Paper-161]
at net.minecraft.server.v1_15_R1.NetworkManager.sendPacket(NetworkManager.java:169) ~[patched_1.15.2.jar:git-Paper-161]
at net.minecraft.server.v1_15_R1.PlayerConnection.a(PlayerConnection.java:1546) ~[?:git-Paper-161]
at net.minecraft.server.v1_15_R1.PlayerConnection.sendPacket(PlayerConnection.java:1519) ~[?:git-Paper-161]
at org.bukkit.craftbukkit.v1_15_R1.entity.CraftPlayer.sendRawMessage(CraftPlayer.java:219) ~[patched_1.15.2.jar:git-Paper-161]
at org.bukkit.craftbukkit.v1_15_R1.entity.CraftPlayer.sendMessage(CraftPlayer.java:226) ~[patched_1.15.2.jar:git-Paper-161]
at net.megaplanet.gamecore.arena.AbstractArena.lambda$21(AbstractArena.java:910) ~[?:?]
at net.megaplanet.gamecore.arena.AbstractArena$$Lambda$4509/000000002F331C60.call(Unknown Source) ~[?:?]
at net.megaplanet.gamecore.player.CorePlayer.executeWhenFullyLoaded(CorePlayer.java:130) ~[?:?]
at net.megaplanet.gamecore.arena.AbstractArena.lambda$8(AbstractArena.java:910) ~[?:?]
at net.megaplanet.gamecore.arena.AbstractArena$$Lambda$4508/000000002F7D24F0.accept(Unknown Source) ~[?:?]
at java.lang.Iterable.forEach(Unknown Source) ~[?:1.8.0_242]
at net.megaplanet.gamecore.arena.AbstractArena.sendMessageToArena(AbstractArena.java:909) ~[?:?]
at net.megaplanet.gamecore.phase.phases.CagePhase.playerJoin(CagePhase.java:161) ~[?:?]
at net.megaplanet.gamecore.phase.phases.CagePhase.playerJoin(CagePhase.java:91) ~[?:?]
at net.megaplanet.gamecore.arena.AbstractArena.addPlayer(AbstractArena.java:595) ~[?:?]
at net.megaplanet.skywars.commands.JoinAreaOverrideCommand.joinCommand(JoinAreaOverrideCommand.java:71) ~[?:?]
at sun.reflect.GeneratedMethodAccessor68.invoke(Unknown Source) ~[?:?]
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_242]
at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_242]
at net.megaplanet.gamecore.command.CommandsManager.executeMethod(CommandsManager.java:739) ~[?:?]
at net.megaplanet.gamecore.command.CommandsManager.executeMethod(CommandsManager.java:673) ~[?:?]
at net.megaplanet.gamecore.command.CommandsManager.executeMethod(CommandsManager.java:596) ~[?:?]
at net.megaplanet.gamecore.command.CommandsManager.execute(CommandsManager.java:575) ~[?:?]
at net.megaplanet.gamecore.CorePlugin.onCommand(CorePlugin.java:261) ~[?:?]
at net.megaplanet.gamecore.command.impl.DynamicPluginCommand.execute(DynamicPluginCommand.java:56) ~[?:?]
at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159) ~[patched_1.15.2.jar:git-Paper-161]
at org.bukkit.craftbukkit.v1_15_R1.CraftServer.dispatchCommand(CraftServer.java:752) ~[patched_1.15.2.jar:git-Paper-161]
at net.minecraft.server.v1_15_R1.PlayerConnection.handleCommand(PlayerConnection.java:1825) ~[?:git-Paper-161]
at net.minecraft.server.v1_15_R1.PlayerConnection.a(PlayerConnection.java:1633) ~[?:git-Paper-161]
at net.minecraft.server.v1_15_R1.PacketPlayInChat.a(PacketPlayInChat.java:47) ~[patched_1.15.2.jar:git-Paper-161]
at net.minecraft.server.v1_15_R1.PacketPlayInChat.a(PacketPlayInChat.java:5) ~[patched_1.15.2.jar:git-Paper-161]
at net.minecraft.server.v1_15_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:23) ~[patched_1.15.2.jar:git-Paper-161]
at net.minecraft.server.v1_15_R1.PlayerConnectionUtils$$Lambda$4287/00000000F50F4320.run(Unknown Source) ~[?:?]
at net.minecraft.server.v1_15_R1.TickTask.run(SourceFile:18) ~[patched_1.15.2.jar:git-Paper-161]
at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.15.2.jar:git-Paper-161]
at net.minecraft.server.v1_15_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.15.2.jar:git-Paper-161]
at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.15.2.jar:git-Paper-161]
at net.minecraft.server.v1_15_R1.MinecraftServer.ba(MinecraftServer.java:1038) ~[patched_1.15.2.jar:git-Paper-161]
at net.minecraft.server.v1_15_R1.MinecraftServer.executeNext(MinecraftServer.java:1031) ~[patched_1.15.2.jar:git-Paper-161]
at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.15.2.jar:git-Paper-161]
at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:1102) ~[patched_1.15.2.jar:git-Paper-161]
at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:934) ~[patched_1.15.2.jar:git-Paper-161]
at java.lang.Thread.run(Unknown Source) [?:1.8.0_242]
```

### Core Information
(_Do not just say "Latest"_)

**Server version**:  git-Paper-161 (MC: 1.15.2)

**AAC version**: 4.3.9

**AACadditionPro version**: 6.1.0

**AACPlus version**: 2.3.1

**ProtocolLib version**: 4.5.1-SNAPSHOT-b445

**Plugin list**: (chat or actionbar plugins?)
MegaCommunicator, PacketListenerApi*, ProtocolLib, SkyWars, TitleManager, ViaBackwards, ViaRewind, ViaRewind-Legacy-Support, ViaVersion

### Special Environment Info
**ViaVersion version**: 3.0.0-SNAPSHOT

**ProtocolSupport version**:  n/a

**ViaBackwards version**: 3.0.0-SNAPSHOT

**BungeeCord plugins**: (chat or actionbar plugins?) n/a

### Configurations
Post your AAC-Hider config **and** AAC language.yml if altered. Or say "default" if untouched.
default

AACPlus Config: 
```
### || AACPLUS || ###
# Developer: https://www.spigotmc.org/members/photon.166336/
# Report issues/errors to the Optimized Config Discord

# || AACPLUSKICK || #
# After how many aacpluskicks should a player be banned?
# The kick count is reset on server restart.
#
# If you don't want to ban just set this to an arbitrarily high number smaller than 2147483647
# Setting this to 0 or a negative number will cause instant bans.
ban_threshold: 2147483640

# The command to be executed when the threshold is reached
ban_command: "ban {player} Illegal client modifications"

# The command ran by console when /aacpluskick is registered
# Allows you to tie the kick into your punishment plugin
# Otherwise, leave this alone for a standard Minecraft kick
kick_command: "minecraft:kick {player} {reason}"

# || REPLACEMENT TEXT || #
# After running /aac, what should a player see instead of AAC's output?
# Be sure to escape special characters according to the java String format with a backslash.
# Color codes utilize the character § (not &)
#
# Multi-line output is NOT possible.
# In order to have multi-line output code a little help-command on your own and execute the command via the commands
# section below. In this case you should utilize the following format, this will make no message appear at all:
# replacement: "{}"
replacement: "Unknown command. Type \"/help\" for help."

# || COMMAND EXECUTION || #
# The following command(s) will be run after a player runs /aac
# You can also run multiple commands with the following format:
# commands:
#    - "first command"
#    - "second command"
#
# Running no commands is possible as well by using the following format:
# commands: "{}"
commands: "aac notify §8§l[§c§lAAC§8§l] §e{player} §fjust ran a command associated with AAC in {world}."

# || AACPLUS EXEMPTIONS || #
# Should players with AAC.admin be exempt from ALL features above?
# Beware: OPs are always bypassed
exempt_admins: true

# Should players with AAC.verbose be exempt from ALL features above?
exempt_verbose: true
```

**Comment by Photon-GitHub** [comment]
Fixed in 2.3.2
