### ISSUE TITLE
NPE On Plugin Enable

### ISSUE THREAD

**Issue by demengc** [Photon-GitHub/AACHider#6]
### Issue Description
When plugin is enabled, an NPE is thrown.

[17:36:36] [Server thread/INFO]: [AACHider] Enabling AACHider v1.4.1
[17:36:36] [Server thread/ERROR]: [AACHider] Loading failed:
[17:36:36] [Server thread/WARN]: java.lang.NullPointerException: at index 0
[17:36:36] [Server thread/WARN]: 	at com.google.common.collect.ObjectArrays.checkElementNotNull(ObjectArrays.java:236)
[17:36:36] [Server thread/WARN]: 	at com.google.common.collect.ImmutableSet.construct(ImmutableSet.java:174)
[17:36:36] [Server thread/WARN]: 	at com.google.common.collect.ImmutableSet.of(ImmutableSet.java:91)
[17:36:36] [Server thread/WARN]: 	at de.photon.aachider.a.<init>(a.java:49)
[17:36:36] [Server thread/WARN]: 	at de.photon.aachider.AACHider.onEnable(AACHider.java:47)
[17:36:36] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:265)
[17:36:36] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:334)
[17:36:36] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:412)
[17:36:36] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugin(CraftServer.java:443)
[17:36:36] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugins(CraftServer.java:357)
[17:36:36] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.MinecraftServer.l(MinecraftServer.java:608)
[17:36:36] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:570)
[17:36:36] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:431)
[17:36:36] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.DedicatedServer.init(DedicatedServer.java:316)
[17:36:36] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:787)
[17:36:36] [Server thread/WARN]: 	at java.lang.Thread.run(Unknown Source)

### Core Information

**Server version**: 
1.13.2

**AAC version**: 
3.6.4

**AACadditionPro version**: 
5.1.0

**AAC-Hider version**: 
1.4.1

**ProtocolLib version**: 
4.4.0-b425

**Plugin list**: (chat or actionbar plugins?)
https://i.imgur.com/iYLbSbo.png

### Special Environment Info
**ViaVersion version**: N/A

**ProtocolSupport version**: 4.29-dev

**ViaBackwards version**:  N/A

**BungeeCord plugins**: N/A

### Configurations
default

AAC-Hider Config: 
default

AAC language.yml: 
default

**Comment by untuned** [comment]
I get the same error on a 1.8.8 server, Paper build 443.
```
[13:18:41 INFO]: [AACHider] Enabling AACHider v1.4.1
[13:18:41 ERROR]: [AACHider] Loading failed:
[13:18:41 WARN]: java.lang.NullPointerException: at index 0
[13:18:41 WARN]:        at com.google.common.collect.ObjectArrays.checkElementNotNull(ObjectArrays.java:240)
[13:18:41 WARN]:        at com.google.common.collect.ImmutableSet.construct(ImmutableSet.java:195)
[13:18:41 WARN]:        at com.google.common.collect.ImmutableSet.of(ImmutableSet.java:105)
[13:18:41 WARN]:        at de.photon.aachider.a.<init>(a.java:49)
[13:18:41 WARN]:        at de.photon.aachider.AACHider.onEnable(AACHider.java:47)
[13:18:41 WARN]:        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321)
[13:18:41 WARN]:        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:332)
[13:18:41 WARN]:        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:407)
[13:18:41 WARN]:        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:359)
[13:18:41 WARN]:        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:318)
[13:18:41 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.s(MinecraftServer.java:408)
[13:18:41 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.k(MinecraftServer.java:372)
[13:18:41 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.a(MinecraftServer.java:327)
[13:18:41 WARN]:        at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:267)
[13:18:41 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:563)
[13:18:41 WARN]:        at java.lang.Thread.run(Thread.java:748)
[13:18:41 INFO]: [AACHider] Loading successful
```

**Comment by CeIebrimbor** [comment]
Set the fastbow message of the language file to some cryptic, randomly generated string. if you set it to nothing, this could happen.

Note: AAC v4.0 will not have forced bow spam messages, so this won't be valid soon.
